### ISSUE TITLE
seems broken in nativescript 3.0

### ISSUE THREAD

**Issue by hazlanmshabli** [bradmartin/nativescript-ripple#12]
I am trying to use this in 3.0 and it complained about ui/core.

**Comment by Dragomir-Ivanov** [comment]
I need this for {N} 3 as well.

**Comment by magar91** [comment]
would be really helpful for me too please. Any update if this plugin will be compatible with version 3?

**Comment by bradmartin** [comment]
It can, I don't have much free time right now to update it. I'll gladly
accept a PR if someone wants to try updating it :) If anyone has questions
and wants to contribute just let me know, always glad to answer questions :)

**Comment by bradmartin** [comment]
2.0.0 has been published. Thanks to @jgraffite for the great PR to update 🎉

**Comment by jgraffite** [comment]
You're welcome @bradmartin . My goal is keep helping and improving that plugin and all the NativeScript community with new helps and plugins

**Comment by Dragomir-Ivanov** [comment]
@jgraffite Thanks a lot for your help. If you have any interest, can you take a look at `nativescript-contacts`. It is a very useful plugin, but no {N} 3.0 support.
