### ISSUE TITLE
Ripple boundaries are always rectangular

### ISSUE THREAD

**Issue by erkanarslan** [bradmartin/nativescript-ripple#15]
If ripple contains a circular element ripple gets out of child element. It always fill the rectangular ripple element. I cannot set border-radius of ripple element.

**Comment by Informateur** [comment]
Have you been able to solve this? This also works in a rectangle.

**Comment by prince30** [comment]
someone please fix this

**Comment by Vetm** [comment]
Having the same problem here. @bradmartin any fix for this?

**Comment by SBD580** [comment]
We use it on a rounded rectangles / circles (on Android only) with the additional properties available ,though not exported, at the native library.

I have created a PR (#20) to support two additional properties, one which can control the border radius of the ripple itself.

**Comment by xeferson** [comment]
@SBD580 it works like a charm.

**Comment by ghost** [comment]
@bradmartin 

Thanks for your work :100: 

What happens to `borderRadius` here, as you sampled an image of a circled button:

![screenshot_2019-02-21-09-46-08](https://user-images.githubusercontent.com/42785945/53155678-dc24c880-35bd-11e9-84ce-27b08c7070b3.png)

Is it broken after that?

Rounded corners/circled images are often used, so would be likely to know what will happen in future here. I tried _NS_ about two years ago and can remember i had those problems at that time.

So, would like to say +1 for safe use of that in future :relaxed: 

btw, i would like to say there is an example for it using normal `borderRadius`

```xml
<RL:Ripple rippleColor="#fff" backgroundColor="#FF4081" borderRadius="30" height="60" width="60">
<Label text="B" fontSize="30" color="#fff" verticalAlignment="center" horizontalAlignment="center" textWrap="true" />
</RL:Ripple>
```

**Comment by ghost** [comment]
I cannot build iOS at home - would be likely to know if there are differences between it and android as i cannot `tns preview` it - thanks for feedback about `rippleBorderRadius` :blush:

**Comment by edusperoni** [comment]
ripple should now respect border-radius
