### ISSUE TITLE
I can't just get this to work.

### ISSUE THREAD

**Issue by riliwanrabo** [bradmartin/nativescript-ripple#17]
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to resume activity {org.nativescript.premiere/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreateView failed

TypeError: com.balysv.materialripple.MaterialRippleLayout is not a constructor
File: "file:///data/data/org.nativescript.premiere/files/app/tns_modules/nativescript-ripple/ripple.js, line: 31, column: 24

StackTrace: 
	Frame: function:'Ripple.createNativeView', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/nativescript-ripple/ripple.js', line: 31, column: 25
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 412, column: 35
	Frame: function:'', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 456, column: 19
	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 455, column: 14
	Frame: function:'', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 456, column: 19
	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 455, column: 14
	Frame: function:'', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 456, column: 19
	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 455, column: 14
	Frame: function:'', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 456, column: 19
	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 455, column: 14
	Frame: function:'', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 456, column: 19
	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 455, column: 14
	Frame: function:'', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 456, column: 19
	Frame: function:'ContentView.eachChildView', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 70, column: 13
	Frame: function:'PageBase.eachChildView', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/page/page-common.js', line: 206, column: 40
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 455, column: 14
	Frame: function:'ViewBase._addViewCore', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 357, column: 18
	Frame: function:'ViewBase._addView', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 346, column: 14
	Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 504, column: 24
	Frame: function:'FragmentClass.onCreateView', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/frame/fragment.js', line: 27, column: 38

	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3400)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3440)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2713)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6077)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
Caused by: com.tns.NativeScriptException: 
Calling js method onCreateView failed

TypeError: com.balysv.materialripple.MaterialRippleLayout is not a constructor
File: "file:///data/data/org.nativescript.premiere/files/app/tns_modules/nativescript-ripple/ripple.js, line: 31, column: 24

StackTrace: 
	Frame: function:'Ripple.createNativeView', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/nativescript-ripple/ripple.js', line: 31, column: 25
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 412, column: 35
	Frame: function:'', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 456, column: 19
	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 455, column: 14
	Frame: function:'', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 456, column: 19
	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 455, column: 14
	Frame: function:'', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 456, column: 19
	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 455, column: 14
	Frame: function:'', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 456, column: 19
	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 455, column: 14
	Frame: function:'', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 456, column: 19
	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 455, column: 14
	Frame: function:'', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 456, column: 19
	Frame: function:'ContentView.eachChildView', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 70, column: 13
	Frame: function:'PageBase.eachChildView', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/page/page-common.js', line: 206, column: 40
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 455, column: 14
	Frame: function:'ViewBase._addViewCore', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 357, column: 18
	Frame: function:'ViewBase._addView', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 346, column: 14
	Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 504, column: 24
	Frame: function:'FragmentClass.onCreateView', file:'file:///data/data/org.nativescript.premiere/files/app/tns_modules/tns-core-modules/ui/frame/fragment.js', line: 27, column: 38

	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
	at com.tns.Runtime.callJSMethod(Runtime.java:957)
	at com.tns.Runtime.callJSMethod(Runtime.java:941)
	at com.tns.Runtime.callJSMethod(Runtime.java:933)
	at com.tns.FragmentClass.onCreateView(FragmentClass.java:40)
	at android.app.Fragment.performCreateView(Fragment.java:2353)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:995)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
	at android.app.BackStackRecord.run(BackStackRecord.java:815)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
	at android.app.FragmentController.execPendingActions(FragmentController.java:371)
	at android.app.Activity.performResume(Activity.java:6760)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3377)
	... 10 more

**Comment by andresjordanze** [comment]
@riliwanrabo Hey I had the same problem, and I fixed with these steps:
`tns platform remove android` && ` tns platform add android`
- Uninstall the app
- Run the app again

I hope it works for you
