### ISSUE TITLE
[Webpack + angular] Ripple is not working

### ISSUE THREAD

**Issue by echap** [bradmartin/nativescript-ripple#6]
Hi @bradmartin and all of you,

I'm trying to webpacking my app, and for an unknown reason, my ripples are not working anymore (the app compiles), but the ripple have no more visual effects and the bindings on it are not working (tap events).

Easily reproduceable with a new project with tns 2.5.2, ns webpack + this plugin on a random view

Any idea ?

**Comment by echap** [comment]
Short answer :
The view registration in `main.ts` has also to be done in the `main.aot.ts` 

Cheers!

**Comment by mn-martin** [comment]
Thank you @echap I was struggling for quite some time now and your comment was the solution!
